modLoader = "javafml"
loaderVersion = "[25,)"
[[mods]]
modId = "weaponmod"
version = "${file.jarVersion}"
displayName = "Balkon's WeaponMod"
displayURL = "https://www.minecraftforum.net/topic/211517-bwm"
logoFile = "bwm_logo.png"
credits = "Thanks for this example mod goes to Java"
authors = "BalkondeurAlpha, ThexXTURBOXx"
description = '''
Throw a spear in a zombie's head!
Cut a skeleton in half with your brand new halberd!
Shoot some slimes in pieces with an old musket!
And more!
'''

[[dependencies.weaponmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.13.2]"
ordering = "NONE"
side = "BOTH"
